=== fill-smart/fill-smart-web/src/i18n/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$ref": "#/definitions/ILocalizedAvailableStrings",
    "definitions": {
        "ILocalizedAvailableStrings": {
            "type": "object",
            "properties": {
                "hello": {
                    "type": "string"
                },
                "productPrice": {
                    "type": "string"
                },
                "noParams": {
                    "type": "string"
                },
                "forgotPassword": {
                    "type": "string"
                },
                "rememberMe": {
                    "type": "string"
                },
                "signIn": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            },
            "required": [
                "hello",
                "productPrice",
                "noParams",
                "forgotPassword",
                "rememberMe",
                "signIn",
                "username",
                "password"
            ],
            "additionalProperties": false
        }
    }
}

=== fill-smart/fill-smart-web/src/i18n/strings_es.json
{
    "hello": "Hola {0}",
    "productPrice": "El precio de {0} es {1} {2}",
    "noParams": "Esta cadena no necesita parametros",
    "forgotPassword": "Olvide mi contraseña",
    "rememberMe": "Recordarme",
    "signIn": "Iniciar Sesion",
    "password": "Contraseña",
    "username": "Usuario"
}
